version: '3.7'
services:
  mongodb_container:
    image: mongo:4.2.10
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - /Users/HarlesBayuAnggara/Documents/docker/database/mongo_database:/data/db

  mysql_container:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - /Users/HarlesBayuAnggara/Documents/docker/database/mysql_database:/docker-entrypoint-initdb.d

  postgres_container:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: harles
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - /Users/HarlesBayuAnggara/Documents/docker/database/postgre_database:/var/lib/postgresql/data